package hu.exprog.beecomposit.back.model;

import java.util.Objects;

import javax.persistence.Basic;

// Generated 2012.09.26. 11:18:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import hu.exprog.honeyweb.front.annotations.EntityFieldInfo;


/**
 * Organization generated by hbm2java
 */
@Entity
@Table(name = "organization", schema = "public")
public class Organization {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;
    
    @EntityFieldInfo(info="#{msg['organization-name']}", weight=1, required=true, editor="txt")    
    @Basic
    String name;

    @EntityFieldInfo(info="#{msg['organization-hqaddress']}", weight=2, required=false, editor="txt")
    @Basic
    @Column(name="hq_address")
    String hqAddress;

    @EntityFieldInfo(info="#{msg['organization-hqphone']}", weight=3, required=false, editor="txt")
    @Basic
    @Column(name="hq_phone")
    String hqPhone;

    @Column(name = "vcard")
    @Lob
    private String vCard;

    @EntityFieldInfo(info="#{msg['description']}", weight=4, required=false, editor="textarea")
    @Column(name = "description")
    private String description;

    @ManyToOne
    @Basic
    @JoinColumn(name = "icon_id")
    private Icon icon;
    
	@Version
	private Long version = 1L;

    public Organization() {
    }

    public Organization(Long id) {
        this.id = id;
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHqAddress() {
		return hqAddress;
	}

	public void setHqAddress(String hqAddress) {
		this.hqAddress = hqAddress;
	}

	public String getHqPhone() {
		return hqPhone;
	}

	public void setHqPhone(String hqPhone) {
		this.hqPhone = hqPhone;
	}

	public String getvCard() {
		return vCard;
	}

	public void setvCard(String vCard) {
		this.vCard = vCard;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Icon getIcon() {
		return icon;
	}

	public void setIcon(Icon icon) {
		this.icon = icon;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		return Objects.hash(description, hqAddress, hqPhone, icon, id, name, vCard, version);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Organization other = (Organization) obj;
		return Objects.equals(description, other.description) && Objects.equals(hqAddress, other.hqAddress)
				&& Objects.equals(hqPhone, other.hqPhone) && Objects.equals(icon, other.icon)
				&& Objects.equals(id, other.id) && Objects.equals(name, other.name)
				&& Objects.equals(vCard, other.vCard) && Objects.equals(version, other.version);
	}

}
