package hu.exprog.beecomposit.back.model;

import javax.persistence.Basic;

// Generated 2012.09.26. 11:18:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import hu.exprog.honeyweb.front.annotations.EntityFieldInfo;


/**
 * Organization generated by hbm2java
 */
@Entity
@Table(name = "organization", schema = "public")
public class Organization implements java.io.Serializable {

    private static final long serialVersionUID = -2376060991535387263L;

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;
    
    @EntityFieldInfo(info="#{msg['organization-name']}", weight=1, required=true, editor="txt")    
    @Basic
    String name;

    @Basic
    @Column(name="hq_address")
    String hqAddress;

    @Basic
    @Column(name="hq_phone")
    String hqPhone;

    @Column(name = "vcard")
    @Lob
    private String vCard;

    @EntityFieldInfo(info="#{msg['description']}", weight=2, required=false, editor="textarea")
    @Column(name = "description")
    private String description;

    @ManyToOne
    @JoinColumn(name = "icon_id")
    private Icon icon;
    
	@Version
	private Long version;

    public Organization() {
    }

    public Organization(Long id) {
        this.id = id;
    }

    public Organization(Long id, String name, String description, Icon icon) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.icon = icon;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getVCard() {
        return this.vCard;
    }
    
    public void setVCard(String vCard) {
    	this.vCard = vCard;
    }

    public Icon getIcon() {
        return this.icon;
    }

    public void setIcon(Icon icon) {
        this.icon = icon;
    }

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getHqAddress() {
		return hqAddress;
	}

	public void setHqAddress(String hqAddress) {
		this.hqAddress = hqAddress;
	}

	public String getHqPhone() {
		return hqPhone;
	}

	public void setHqPhone(String hqPhone) {
		this.hqPhone = hqPhone;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((hqAddress == null) ? 0 : hqAddress.hashCode());
		result = prime * result + ((hqPhone == null) ? 0 : hqPhone.hashCode());
		result = prime * result + ((description == null) ? 0 : description.hashCode());
		result = prime * result + ((icon == null) ? 0 : icon.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((vCard == null) ? 0 : vCard.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Organization other = (Organization) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (hqAddress == null) {
			if (other.hqAddress != null)
				return false;
		} else if (!hqAddress.equals(other.hqAddress))
			return false;
		if (hqPhone == null) {
			if (other.hqPhone != null)
				return false;
		} else if (!hqPhone.equals(other.hqPhone))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (icon == null) {
			if (other.icon != null)
				return false;
		} else if (!icon.equals(other.icon))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (vCard == null) {
			if (other.vCard != null)
				return false;
		} else if (!vCard.equals(other.vCard))
			return false;
		return true;
	}
}
